# gh-run-delete
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-run-delete.1.gz
complete -c gh-run-delete -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXAMPLE'

