# gh-repo-unarchive
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-repo-unarchive.1.gz
complete -c gh-repo-unarchive -s y -l yes -d 'Skip the confirmation prompt SEE ALSO'

