# gh-ssh-key-delete
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-ssh-key-delete.1.gz
complete -c gh-ssh-key-delete -s y -l yes -d 'Skip the confirmation prompt SEE ALSO'

