# podchecker
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/podchecker.1.gz
complete -c podchecker -o help
complete -c podchecker -o man
complete -c podchecker -o warnings -o nowarnings

