# sl
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/sl.1.gz
complete -c sl -s a -d 'An accident is occurring.  People cry for help'
complete -c sl -s l -d 'Little version'
complete -c sl -s F -d 'It flies like the galaxy express 999'
complete -c sl -s c -d 'C51 appears instead of D51'

